
package org.xzc.services2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FirstWsNoName", targetNamespace = "http://impl.service.xzc.org/", wsdlLocation = "http://xzc:8080/spring_and_cxf/services/services2?wsdl")
public class FirstWsNoName
    extends Service
{

    private final static URL FIRSTWSNONAME_WSDL_LOCATION;
    private final static WebServiceException FIRSTWSNONAME_EXCEPTION;
    private final static QName FIRSTWSNONAME_QNAME = new QName("http://impl.service.xzc.org/", "FirstWsNoName");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://xzc:8080/spring_and_cxf/services/services2?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FIRSTWSNONAME_WSDL_LOCATION = url;
        FIRSTWSNONAME_EXCEPTION = e;
    }

    public FirstWsNoName() {
        super(__getWsdlLocation(), FIRSTWSNONAME_QNAME);
    }

    public FirstWsNoName(WebServiceFeature... features) {
        super(__getWsdlLocation(), FIRSTWSNONAME_QNAME, features);
    }

    public FirstWsNoName(URL wsdlLocation) {
        super(wsdlLocation, FIRSTWSNONAME_QNAME);
    }

    public FirstWsNoName(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FIRSTWSNONAME_QNAME, features);
    }

    public FirstWsNoName(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FirstWsNoName(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FirstWs
     */
    @WebEndpoint(name = "FirstWsImplPort")
    public FirstWs getFirstWsImplPort() {
        return super.getPort(new QName("http://impl.service.xzc.org/", "FirstWsImplPort"), FirstWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FirstWs
     */
    @WebEndpoint(name = "FirstWsImplPort")
    public FirstWs getFirstWsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.xzc.org/", "FirstWsImplPort"), FirstWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FIRSTWSNONAME_EXCEPTION!= null) {
            throw FIRSTWSNONAME_EXCEPTION;
        }
        return FIRSTWSNONAME_WSDL_LOCATION;
    }

}
