
package org.xzc.service.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.xzc.service.ObjectFactory;
import org.xzc.service.User;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "first_ws", targetNamespace = "http://service.xzc.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FirstWs {


    /**
     * 
     * @param user2
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHiToUser", targetNamespace = "http://service.xzc.org/", className = "org.xzc.service.SayHiToUser")
    @ResponseWrapper(localName = "sayHiToUserResponse", targetNamespace = "http://service.xzc.org/", className = "org.xzc.service.SayHiToUserResponse")
    public String sayHiToUser(
        @WebParam(name = "user2", targetNamespace = "")
        User user2);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "sayNothing", targetNamespace = "http://service.xzc.org/", className = "org.xzc.service.SayNothing")
    @ResponseWrapper(localName = "sayNothingResponse", targetNamespace = "http://service.xzc.org/", className = "org.xzc.service.SayNothingResponse")
    public void sayNothing();

    /**
     * 
     * @return
     *     returns org.xzc.service.GetUserMapResponse.Return
     */
    @WebMethod
    @WebResult(name = "_return", targetNamespace = "")
    @RequestWrapper(localName = "getUserMap", targetNamespace = "http://service.xzc.org/", className = "org.xzc.service.GetUserMap")
    @ResponseWrapper(localName = "getUserMapResponse", targetNamespace = "http://service.xzc.org/", className = "org.xzc.service.GetUserMapResponse")
    public org.xzc.service.GetUserMapResponse.Return getUserMap();

    /**
     * 
     * @return
     *     returns java.util.List<org.xzc.service.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserList", targetNamespace = "http://service.xzc.org/", className = "org.xzc.service.GetUserList")
    @ResponseWrapper(localName = "getUserListResponse", targetNamespace = "http://service.xzc.org/", className = "org.xzc.service.GetUserListResponse")
    public List<User> getUserList();

    /**
     * 
     * @param name1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://service.xzc.org/", className = "org.xzc.service.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://service.xzc.org/", className = "org.xzc.service.SayHiResponse")
    public String sayHi(
        @WebParam(name = "name1", targetNamespace = "")
        String name1);

}
